



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamelathinh;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.border.Border;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author DELL
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    Player[] listplayer = new Player[10];
    JLabel[] listLabel = new JLabel[10];
    Border blackline = BorderFactory.createLineBorder(Color.black);
    Border redline = BorderFactory.createLineBorder(Color.red);

    public NewJPanel(NewJFrame obj) {
        initComponents();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        JLabel title = new JLabel("Ranking List");
        title.setFont(new Font("Serif", Font.PLAIN, 30));
        title.setHorizontalAlignment(JLabel.CENTER);
        title.setBorder(blackline);
        this.add(title);
        preventNull();
        listplayer = readFile(listplayer);
        for (int k = 0; k < 10; k++) {
            listLabel[k] = new JLabel();
            listLabel[k].setFont(new Font("Serif", Font.PLAIN, 30));
            listLabel[k].setText(k + 1 + "." + listplayer[k].getName() + " " + listplayer[k].getScore());
            this.add(listLabel[k]);
        }
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                obj.glassPane.setVisible(false);
                obj.glassPane.disable();
            }
        });
    }
     public void preventNull() {
        for (int i = 0; i < 10; i++) {
            listplayer[i] = new Player();
            if (listplayer[i].getName() == null) {
                listplayer[i].setName("----");
                listplayer[i].setScore(0);
            }
        }
    }

     public Player[] readFile(Player[] list) {
        try {
            FileInputStream fi = new FileInputStream(new File("rank\\\\rank.txt"));
            ObjectInputStream oi = new ObjectInputStream(fi);
            list = (Player[]) oi.readObject();
            // Read objects
            oi.close();
            fi.close();

        } catch (ClassNotFoundException ex) {
        } catch (IOException e) {

        }
        return list;
    }
     
    public void updateRanking(Player[] listplayer) {
        for (int k = 0; k < 10; k++) {
            listLabel[k].setText(k + 1 + "." + listplayer[k].getName() + " " + listplayer[k].getScore());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
